version: '3.1'

services:

  fuseki:
    ## Example:
    ## command: [ "--tdb2", "--update", "--loc", "databases/DB2", "/ds" ]
    build:
      context: jena-fuseki-docker-4.9.0/
      dockerfile: Dockerfile
    image: fuseki
    ports:
      - "3030:3030"
    volumes:
      - ./jena-fuseki-docker-4.9.0/logs:/fuseki/logs
      - ./jena-fuseki-docker-4.9.0/databases:/fuseki/databases
    command: ["--update", "--loc", "databases/MEM", "/modelg"]

  flask:
    build: 
      context: .
      dockerfile: flask_docker/Dockerfile

    #command: /bin/bash
    #stdin_open: true # docker run -i
    #tty: true # docker run -t
    ports:
      - "5000:5000"
    volumes:
      - ./flask-app:/app
      - ./src:/src

    command: [ "flask", "run","--host","0.0.0.0","--port","5000"]

    depends_on:
      - fuseki