PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 

select distinct ?g ?created ?description ?label (COUNT(?s) as ?triples)
    WHERE
    {GRAPH ?g { ?s ?p ?o. 
		?g a <http://www.tkltd.org/ontologies/graphs#UserGraph>.
		?g <http://purl.org/dc/elements/1.1/created> ?created. 
		OPTIONAL { ?g <http://purl.org/dc/elements/1.1/description> ?description} . 
		OPTIONAL { ?g rdfs:label ?label. }}

}
GROUP BY ?g ?created ?description ?label